### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by yantrab** [syncfusion/ej2-ng-samples#1]
npm WARN deprecated es6-module-loader@0.17.11: This project has been deprecated for "npm install es-module-loader" based on the newer loader spec.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated express@2.5.11: express 2.x series is deprecated
npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @syncfusion/ej2-compression@^0.4.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@syncfusion/ej2'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\arkadiy\AppData\Roaming\npm-cache\_logs\2017-10-18T12_43_51_142Z-debug.log

**Comment by ajithr** [comment]
Hi @yantrab,

Thanks for your interest in Essential JS 2, We have resolved the npm install failure in [ej2](https://www.npmjs.com/package/@syncfusion/ej2) package. Could you please reinstall the packages in the `ej2-ng-samples` application?

Regards,
Ajith R
