### ISSUE TITLE
unexpected closing </trbody>

### ISSUE THREAD

**Issue by estettin** [syncfusion/ej2-ng-samples#10]
src/circular-gauge/range.html
line 113

**Comment by estettin** [comment]
also in src/circular-gauge/multiple-axis.html line 81

**Comment by estettin** [comment]
also in src/circular-gauge/user-interactions.html line 60

**Comment by ghost** [comment]
Hi Estettin,

Sorry for the inconvenience.

We have validated your query and we will remove the unwanted code snippet from our circular gauge angular repository. It will be rolled out in our Volume 2 main release which is expected to be out at the end of June 2019.

Regards,
Baby.
