### ISSUE TITLE
Localization doesn't work

### ISSUE THREAD

**Issue by j-nord** [syncfusion/ej2-ng-samples#2]
Hi,

we change from Version 1.0x to Version 15.4.17. Since this change the localization doesn't work.

**app.module.ts:**

import { loadCldr, setCulture, setCurrencyCode } from '@syncfusion/ej2-base';
loadCldr(
    require('./localization/cldr-data/de/currencies.json'),
    require('./localization/cldr-data/de/ca-gregorian.json'),
    require('./localization/cldr-data/de/numbers.json'),
    require('./localization/cldr-data/de/timeZoneNames.json'),
    require('./localization/cldr-data/de/numberingSystems.json')
)

// Syncfusion
setCulture("de");
setCurrencyCode('EUR');

Why?

Regards

j.nord

**Comment by Mydeen-SN** [comment]
Hi j-nord,
 
We have validated the reported issue and we are unable to reproduce the issue on our side. We have prepared a simple sample with the setCulture method in angular CLI. 

Please find the sample link as below

https://github.com/SyncfusionSamples/ej2-angular-setCulture

If you are still facing the same issue again, please share us the below details.
1.	Share us the replication procedure.
2.	Share the full code snippet.
3.	Provide us the sample or modify the given sample with issue replication steps.

Regards,
Mydeen S N

**Comment by j-nord** [comment]
Hi Mydeen,

we have found the error. we have delete the node-modules directory and restore the modules. After this it works.

thanks

j.nord
