### ISSUE TITLE
license

### ISSUE THREAD

**Issue by chenzeshenga** [syncfusion/ej2-ng-samples#25]
hi syncfusion team,

is this project and its dependency under open source license and can this project be used by personal?

looking forward of your reply.

**Comment by bharathm03** [comment]
@chenzeshenga this project is under Syncfusion licensing terms. Refer to the following locations for more information.

https://github.com/syncfusion/ej2-angular-samples/blob/master/license 
https://www.syncfusion.com/sales/products#special-license

**Comment by chenzeshenga** [comment]
> @chenzeshenga this project is under Syncfusion licensing terms. Refer to the following locations for more information.
> 
> https://github.com/syncfusion/ej2-angular-samples/blob/master/license
> https://www.syncfusion.com/sales/products#special-license

thanks
