### ISSUE TITLE
Checkout - compile not working

### ISSUE THREAD

**Issue by thor089** [syncfusion/ej2-ng-samples#26]
Hi

I wanted to have a look on the solution.
1. I cloned the repo
2. npm install 
3. npm run ship-source     => this lead to an issue with node 12 (primordials is not defined in node) => downgrade to node 11
4. npm run ship-source  OK
5. npm run start 

ERROR in src/app/rich-text-editor/markdown-editor-custom-format.component.ts(9,25): error TS2307: Cannot find module 'marked'.
src/app/rich-text-editor/markdown-editor-preview.component.ts(9,25): error TS2307: Cannot find module 'marked'.
src/app/rich-text-editor/markdown-editor.component.ts(10,25): error TS2307: Cannot find module 'marked'.
src/app/rich-text-editor/tribute.component.ts(7,22): error TS2307: Cannot find module 'tributejs'.

I appreciate your help.

Regards,
Thorsten

**Comment by gurunathancs1991** [comment]
Hi @thor089 

We have resolved the issue in our end. Kindly pull the latest and ensure at your end.

Regards,
Gurunathan

**Comment by thor089** [comment]
Thank you Gurunathan - now it's working

Regards,
Thorsten
