### ISSUE TITLE
Data grid excel filters do not work

### ISSUE THREAD

**Issue by PascalTemel** [syncfusion/ej2-ng-samples#5]
![image](https://user-images.githubusercontent.com/13536271/50692769-3c26d600-1035-11e9-85b4-239b3f88d34a.png)

**Comment by Madhust** [comment]
@PascalTemel We are able to see the reported issue. We will refresh the sample browser with the fix by January 17, 2018. Until then we appreciate your patience.

**Comment by Madhust** [comment]
@PascalTemel Sorry for the delay in get back to you and also thanks for your patience. Now the reported problem has been resolved and our sample browser is refreshed.
