### ISSUE TITLE
Typo in file at /src/chart/smart-axis-labels.html line 115

### ISSUE THREAD

**Issue by estettin** [syncfusion/ej2-ng-samples#9]
missing double quotation (") and > to opening <a> tag and also a closing </a> and </p>

should be: 
```
<p>
        More information on the smart axis labels can be found in this
        <a target="_blank" href="https://ej2.syncfusion.com/angular/documentation/chart/axis-labels/#smart-axis-labels"></a>
    </p>
```

**Comment by ghost** [comment]
Hi Estettin,

Sorry for the inconvenience.

We have validated your query and we will change the code snippet in our chart angular repository. It will be rolled out in our Volume 2 main release which is expected to be out at the end of June 2019.


Regards,
Baby.
